---
# handlers file for LEMP_Stack

- name: Reload Apache
  ansible.builtin.service:
    name: httpd
    state: reloaded
    enabled: yes

- name: Restart Mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: yes


